@StokTakip_Core_API_HostAddress = http://localhost:5185


GET {{StokTakip_Core_API_HostAddress}}/api/urunler
Accept: application/json
  


###
POST {{StokTakip_Core_API_HostAddress}}/api/urunler
Content-Type: application/json

{
  "urunAdi": "2026test - Duzeltilmis",
  "birimFiyat": 23.43,
  "stokMiktari": 23,
  "kategoriID": 4
}


