@StokTakip_Core_API_HostAddress = http://localhost:5185

##listeleme işlemleri
GET {{StokTakip_Core_API_HostAddress}}/api/urunler
Accept: application/json
  


### ürün ekleme işlemi
POST {{StokTakip_Core_API_HostAddress}}/api/urunler
Content-Type: application/json

{
  "urunAdi": "2026test - Duzeltilmis",
  "birimFiyat": 23.43,
  "stokMiktari": 23,
  "kategoriID": 4
}

### ürün güncelleme işlemi
PUT {{StokTakip_Core_API_HostAddress}}/api/urunler/26
Content-Type: application/json

{
  "urunAdi": "Guncelleme denemesi 2",
  "birimFiyat": 919.99,
  "stokMiktari": 12,
  "kategoriID": 1
}

### Ürün silme işlemi
DELETE {{StokTakip_Core_API_HostAddress}}/api/urunler/24

### kategori listeleme işlemi
POST {{StokTakip_Core_API_HostAddress}}/api/stokhareketleri
Content-Type: application/json

{
  "urunID": 21,
  "islemTuru": "Giriş",
  "miktar": 10,
  "aciklama": "yeni alım yapıldı"
}

### Kategori Ekleme
POST {{StokTakip_Core_API_HostAddress}}/api/kategoriler
Content-Type: application/json

{
  "kategoriAdi": "Test"
}

### Stok Hareketi Güncelleme
POST {{StokTakip_Core_API_HostAddress}}/api/stokhareketleri
Content-Type: application/json

{
  "urunID": 4, 
  "islemTuru": "Cikis",
  "miktar": 999,
  "aciklama": "Repository Pattern Test Girişi"
}

### İşlem Geçmişi Listeleme
GET {{StokTakip_Core_API_HostAddress}}/api/islemgecmisi

@HostAddress = http://localhost:5185


### admin girişi yaparak token alma 
POST https://localhost:7140/api/auth/login
Content-Type: application/json

{
  "kullaniciAdi": "admin",
  "sifre": "1234"
}

### token ile ürün listeleme işlemi yapma 
GET https://localhost:7140/api/urunler
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzgwODIyMTI2LCJleHAiOjE3ODA4NTA5MjYsImlhdCI6MTc4MDgyMjEyNiwiaXNzIjoiU3Rva1Rha2lwQVBJIiwiYXVkIjoiU3Rva1Rha2lwQ2xpZW50In0.gJl39vAZzdLHxM7pDEmg8M4j_b2PJICKCTUE5-9QYxs


### İlk Kurulum İşlemi (Admin Kullanıcı Oluşturma)
POST {{StokTakip_Core_API_HostAddress}}/api/auth/ilk-kurulum
Accept: application/json