@StokTakip_Core_API_HostAddress = http://localhost:5185

## ürün listeleme işlemi
GET {{StokTakip_Core_API_HostAddress}}/api/urunler
Accept: application/json
  


### ürün ekleme işlemi
POST {{StokTakip_Core_API_HostAddress}}/api/urunler
Content-Type: application/json

{
  "urunAdi": "2026test - Duzeltilmis",
  "birimFiyat": 23.43,
  "stokMiktari": 23,
  "kategoriID": 4
}

### ürün güncelleme işlemi
PUT {{StokTakip_Core_API_HostAddress}}/api/urunler/24
Content-Type: application/json

{
  "urunAdi": "Guncelleme denemesi",
  "birimFiyat": 919.99,
  "stokMiktari": 12,
  "kategoriID": 1
}

### Ürün silme işlemi
DELETE {{StokTakip_Core_API_HostAddress}}/api/urunler/24

### kategori listeleme işlemi
POST {{StokTakip_Core_API_HostAddress}}/api/stokhareketleri
Content-Type: application/json

{
  "urunID": 21,
  "islemTuru": "Giriş",
  "miktar": 10,
  "aciklama": "yeni alım yapıldı"
}

